---
title: "[Q#19307622][A#19309163] Java new File() says FileNotFoundException but file exists"
question_title: "Java new File() says FileNotFoundException but file exists"
question_text: "I have an assignment for my CS class where it says to read a file with several test scores and asks me to sum and average them. While summing and averaging is easy, I am having problems with the file reading. The instructor said to use this syntax However, this throws a FileNotFoundException, but I have checked over and over again to see if the file exists in the current folder, and after that, I figured that it had to do something with the permissions. I changed the permissions for read and write for everyone, but it still did not work and it still keeps throwing the error. Does anyone have any idea why this may be occurring? EDIT: It was actually pointing to a directory up, however, I have fixed that problem. file.exists() returns true, however, when I try to put it in the scanner, it throws the filenotfoundexception Here is all my code"
answer_text: "There are three cases where a FileNotFoundException may be thrown. The first two cases are unlikely based on your description. I would test against the third case using file.canRead(). If the test above returns true, I would suspect the following: You might have forgotten to explicitly throw or catch the potential exception (i.e., FileNotFoundExcetion). If you work in an IDE, you should have got some complaint from the compiler. But I suspect you didn't run your code in such an IDE. I've just run your code without taking care of the complaint from Netbeans, only to get the following exception message: Exception in thread \"main\" java.lang.RuntimeException: Uncompilable   source code - unreported exception java.io.FileNotFoundException; must   be caught or declared to be thrown Try the following code and see if the exception would be gone:"
apization_code: "package com.stackoverflow.api;  import com.sun.java_cup.internal.runtime.Scanner; import java.io.File; import java.io.FileNotFoundException;  /**  * Java new File() says FileNotFoundException but file exists  *  * @author APIzator  * @see <a href=\"https://stackoverflow.com/a/19309163\">https://stackoverflow.com/a/19309163</a>  */ public class APIzator19309163 {    public static Scanner exist() throws FileNotFoundException {     File file = new File(\"scores.dat\");     System.out.println(file.exists());     return new Scanner(file);   } }"
---

https://stackoverflow.com/q/19307622

I have an assignment for my CS class where it says to read a file with several test scores and asks me to sum and average them. While summing and averaging is easy, I am having problems with the file reading. The instructor said to use this syntax
However, this throws a FileNotFoundException, but I have checked over and over again to see if the file exists in the current folder, and after that, I figured that it had to do something with the permissions. I changed the permissions for read and write for everyone, but it still did not work and it still keeps throwing the error. Does anyone have any idea why this may be occurring?
EDIT: It was actually pointing to a directory up, however, I have fixed that problem. file.exists() returns true, however, when I try to put it in the scanner, it throws the filenotfoundexception
Here is all my code


<div class="code-logo"><img src="/stackoverflow.png" /></div>

```java
Scanner scores=new Scanner(new File("scores.dat"));
import java.util.Scanner;
import java.io.*;
public class readInt{
        public static void main(String args[]){
                File file=new File("lines.txt");
                System.out.println(file.exists());
                Scanner scan=new Scanner(file);
        }
}
```


## Original code snippet

https://stackoverflow.com/a/19309163

There are three cases where a FileNotFoundException may be thrown.
The first two cases are unlikely based on your description. I would test against the third case using file.canRead().
If the test above returns true, I would suspect the following:
You might have forgotten to explicitly throw or catch the potential exception (i.e., FileNotFoundExcetion). If you work in an IDE, you should have got some complaint from the compiler. But I suspect you didn&#x27;t run your code in such an IDE.
I&#x27;ve just run your code without taking care of the complaint from Netbeans, only to get the following exception message:
Exception in thread &quot;main&quot; java.lang.RuntimeException: Uncompilable
  source code - unreported exception java.io.FileNotFoundException; must
  be caught or declared to be thrown
Try the following code and see if the exception would be gone:

<div class="code-logo"><img src="/stackoverflow.png" /></div>

```java
public static void main(String[] args) throws FileNotFoundException {    
    File file=new File("scores.dat");
    System.out.println(file.exists());
    Scanner scan=new Scanner(file);
}
```

## Produced APIzation

[`APIzator19309163.java`](https://github.com/pasqualesalza/apization-temp-data/raw/master/search/APIzator19309163.java)

<div class="code-logo"><img src="/apizator.png" /></div>

```java
package com.stackoverflow.api;

import com.sun.java_cup.internal.runtime.Scanner;
import java.io.File;
import java.io.FileNotFoundException;

/**
 * Java new File() says FileNotFoundException but file exists
 *
 * @author APIzator
 * @see <a href="https://stackoverflow.com/a/19309163">https://stackoverflow.com/a/19309163</a>
 */
public class APIzator19309163 {

  public static Scanner exist() throws FileNotFoundException {
    File file = new File("scores.dat");
    System.out.println(file.exists());
    return new Scanner(file);
  }
}

```