---
title: "[Q#8146793][A#8147238] No suitable driver found for 'jdbc:mysql://localhost:3306/mysql"
question_title: "No suitable driver found for 'jdbc:mysql://localhost:3306/mysql"
question_text: "Using Java, I get this error when attempting to connect to a mysql database: I'm using the mysql-connector-java-5.1.18-bin.jar driver.  It is in my build path.  I have restarted MySQL.  I've also logged on from the command line with root and no password and it connected fine.  I'm not currently seeing a port 3306 in netstat.  Previously I was getting a different error (I didn't change the code).  The error was \"jdbc mysql Access denied for user 'root'@'localhost password NO\""
answer_text: "In this particular case (assuming that the Class#forName() didn't throw an exception; your code is namely continuing with running instead of throwing the exception), this SQLException means that Driver#acceptsURL() has returned false for any of the loaded drivers. And indeed, your JDBC URL is wrong: Remove the singlequote:"
apization_code: "package com.stackoverflow.api;  /**  * No suitable driver found for 'jdbc:mysql://localhost:3306/mysql  *  * @author APIzator  * @see <a href=\"https://stackoverflow.com/a/8147238\">https://stackoverflow.com/a/8147238</a>  */ public class APIzator8147238 {    public static void find(String url, String url) throws RuntimeException {} }"
---

https://stackoverflow.com/q/8146793

Using Java, I get this error when attempting to connect to a mysql database:
I&#x27;m using the mysql-connector-java-5.1.18-bin.jar driver.  It is in my build path.  I have restarted MySQL.  I&#x27;ve also logged on from the command line with root and no password and it connected fine.  I&#x27;m not currently seeing a port 3306 in netstat.  Previously I was getting a different error (I didn&#x27;t change the code).  The error was &quot;jdbc mysql Access denied for user &#x27;root&#x27;@&#x27;localhost password NO&quot;


<div class="code-logo"><img src="/stackoverflow.png" /></div>

```java
java.sql.SQLException: No suitable driver found for 
jdbc:mysql://localhost:3306/mysql at
java.sql.DriverManager.getConnection(Unknown Source)
at java.sql.DriverManager.getConnection(Unknown Source)
at MyTest1.main(MyTest1.java:28)
try {
    Class.forName("com.mysql.jdbc.Driver");
} 
catch (ClassNotFoundException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
} 


try {
    String url = "jdbc:mysql://localhost:3306/mysql";
    Connection con = DriverManager.getConnection(url, "root", "");
}
catch (Exception e){
    e.printStackTrace();
}
```


## Original code snippet

https://stackoverflow.com/a/8147238

In this particular case (assuming that the Class#forName() didn&#x27;t throw an exception; your code is namely continuing with running instead of throwing the exception), this SQLException means that Driver#acceptsURL() has returned false for any of the loaded drivers.
And indeed, your JDBC URL is wrong:
Remove the singlequote:

<div class="code-logo"><img src="/stackoverflow.png" /></div>

```java
String url = "'jdbc:mysql://localhost:3306/mysql";
String url = "jdbc:mysql://localhost:3306/mysql";
```

## Produced APIzation

[`APIzator8147238.java`](https://github.com/pasqualesalza/apization-temp-data/raw/master/search/APIzator8147238.java)

<div class="code-logo"><img src="/apizator.png" /></div>

```java
package com.stackoverflow.api;

/**
 * No suitable driver found for 'jdbc:mysql://localhost:3306/mysql
 *
 * @author APIzator
 * @see <a href="https://stackoverflow.com/a/8147238">https://stackoverflow.com/a/8147238</a>
 */
public class APIzator8147238 {

  public static void find(String url, String url) throws RuntimeException {}
}

```